# -*- mode: org; coding: utf-8; -*-
#+TITLE:     Emacs Berlin Beginners Curriculum
#+AUTHOR:    Emacs Berlin
#+EMAIL:
#+DATE:
#+DESCRIPTION: A modern beginners guide to setting up and using Emacs.
#+KEYWORDS:
#+LANGUAGE:  en
#+LINK_UP:
#+LINK_HOME:
#+XSLT:

#+HTML_HEAD: <meta charset="utf-8" />
#+HTML_HEAD: <meta name="viewport" content="width=device-width, initial-scale=1.0" />
#+HTML_HEAD: <link rel="stylesheet" href="css/foundation.css" />
#+HTML_HEAD: <link rel="stylesheet" href="css/screen.css" />
#+HTML_HEAD: <link rel="stylesheet" href="css/curriculum.css" />
#+HTML_HEAD: <script src="js/vendor/modernizr.js"></script>
#+HTML_HEAD: <link href='http://fonts.googleapis.com/css?family=Lato:400,900,400italic,900italic' rel='stylesheet' type='text/css'>

* Author information                                               :noexport:

This is intended as a basic introduction to using and configuring Emacs. It goes
from installing emacs up to having the most important things configured and the
most essential packages installed. In between it covers the basics of editing
and navigating, and introduces just enough Emacs Lisp to start configuring
things.

It is geared towards people with a little bit of programming experience, but no
knowledge of Emacs. Together with an experienced Emacser they should be able to
follow this guide top to bottom in under four hours, ending up with a working
setup and enough knowledge to start coding in Emacs.

Some guidelines

- aim for a light, conversational style, prefer [[https://xkcd.com/1133/][small words over large ones]]
- show don't tell. Instead of long-winded, in-depth explanations prefer a few
  chosen examples.
- go for a modern approach, including elpa/melpa, use-package, customize
- this is not a manual, people can learn about the finer points of Emacs and
  Elisp elsewhere

* Installation

How to install Emacs depends on your operating system. Make sure you install
"GNU Emacs", and not an alternative version like "XEmacs" or "Aquamacs".

** Windows

Windows versions of GNU Emacs are distributed as zip-files, which can be found
on [[http://ftpmirror.gnu.org/emacs/windows/][gnu.org ftp mirrors]]. Find the zip file with the highest version number, at
time of writing this is ~emacs-24.5-bin-i686-mingw32.zip~, and download it.

Create a directory where you want to put Emacs, for example ~C:\Program
Files\Emacs~ and unpack the zip file there.

The ~runemacs.exe~ program in the ~bin~ directory will start Emacs. The
~addpm.exe~ program will add Emacs to the start menu.

** OS X

OS X already comes with a version of Emacs installed, but it's very old (Emacs
22), and it doesn't have GUI support, so it only works inside a terminal. You
want to avoid using this version.

If you have Homebrew available then that is the most straightforward option.

#+BEGIN_SRC
$ brew update
$ brew install emacs --with-cocoa
$ brew linkapps emacs
#+END_SRC

Alternatively you can download a ~.dmg~ at [[https://emacsformacosx.com/][emacsformacosx.com]].

That should be enough to get you going. Emacs Redux has some more tips on
[[http://emacsredux.com/blog/2015/05/09/emacs-on-os-x/][setting up Emacs on OS X]].

** Linux

Your package manager should have ready-made packages available. If you have a
graphical package manager look for an "emacs" package, or install the package
from the command line with ~apt-get~ or ~yum~.

* First steps
** Basic editing, kill/yank
** Visiting files
** Switching buffers
* First steps in Elisp
** evaluating forms
** values, variables, functions, setq
* create first .emacs/init.el
** major/minor modes
** set up elpa
** set up use-package
** get to a "good enough" initial set up
* Where next
** how to use the help system
** a tour of emacs features and packages
